name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Tests
      id: tests
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Tests
        setup-command: javac ./Exercises/*
        command: java Tests.java
        input: ''
        expected-output: 'true'
        comparison-method: exact
        timeout: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS_RESULTS: "${{steps.tests.outputs.result}}"
      with:
        runners: tests
